
/**
 * Auto-generated mapping between Surah IDs and Semantic Slugs.
 */

// Map ID (number) -> Slug (string)
export const SURAH_ID_TO_SLUG: Record<number, string> = {
    "1": "surah-al-fatihah",
    "2": "surah-al-baqarah",
    "3": "surah-ali-imran",
    "4": "surah-an-nisa",
    "5": "surah-al-maidah",
    "6": "surah-al-anam",
    "7": "surah-al-araf",
    "8": "surah-al-anfal",
    "9": "surah-at-tawbah",
    "10": "surah-yunus",
    "11": "surah-hud",
    "12": "surah-yusuf",
    "13": "surah-ar-rad",
    "14": "surah-ibrahim",
    "15": "surah-al-hijr",
    "16": "surah-an-nahl",
    "17": "surah-al-isra",
    "18": "surah-al-kahf",
    "19": "surah-maryam",
    "20": "surah-taha",
    "21": "surah-al-anbya",
    "22": "surah-al-hajj",
    "23": "surah-al-muminun",
    "24": "surah-an-nur",
    "25": "surah-al-furqan",
    "26": "surah-ash-shuara",
    "27": "surah-an-naml",
    "28": "surah-al-qasas",
    "29": "surah-al-ankabut",
    "30": "surah-ar-rum",
    "31": "surah-luqman",
    "32": "surah-as-sajdah",
    "33": "surah-al-ahzab",
    "34": "surah-saba",
    "35": "surah-fatir",
    "36": "surah-ya-sin",
    "37": "surah-as-saffat",
    "38": "surah-sad",
    "39": "surah-az-zumar",
    "40": "surah-ghafir",
    "41": "surah-fussilat",
    "42": "surah-ash-shuraa",
    "43": "surah-az-zukhruf",
    "44": "surah-ad-dukhan",
    "45": "surah-al-jathiyah",
    "46": "surah-al-ahqaf",
    "47": "surah-muhammad",
    "48": "surah-al-fath",
    "49": "surah-al-hujurat",
    "50": "surah-qaf",
    "51": "surah-adh-dhariyat",
    "52": "surah-at-tur",
    "53": "surah-an-najm",
    "54": "surah-al-qamar",
    "55": "surah-ar-rahman",
    "56": "surah-al-waqiah",
    "57": "surah-al-hadid",
    "58": "surah-al-mujadila",
    "59": "surah-al-hashr",
    "60": "surah-al-mumtahanah",
    "61": "surah-as-saf",
    "62": "surah-al-jumuah",
    "63": "surah-al-munafiqun",
    "64": "surah-at-taghabun",
    "65": "surah-at-talaq",
    "66": "surah-at-tahrim",
    "67": "surah-al-mulk",
    "68": "surah-al-qalam",
    "69": "surah-al-haqqah",
    "70": "surah-al-maarij",
    "71": "surah-nuh",
    "72": "surah-al-jinn",
    "73": "surah-al-muzzammil",
    "74": "surah-al-muddaththir",
    "75": "surah-al-qiyamah",
    "76": "surah-al-insan",
    "77": "surah-al-mursalat",
    "78": "surah-an-naba",
    "79": "surah-an-naziat",
    "80": "surah-abasa",
    "81": "surah-at-takwir",
    "82": "surah-al-infitar",
    "83": "surah-al-mutaffifin",
    "84": "surah-al-inshiqaq",
    "85": "surah-al-buruj",
    "86": "surah-at-tariq",
    "87": "surah-al-ala",
    "88": "surah-al-ghashiyah",
    "89": "surah-al-fajr",
    "90": "surah-al-balad",
    "91": "surah-ash-shams",
    "92": "surah-al-layl",
    "93": "surah-ad-duhaa",
    "94": "surah-ash-sharh",
    "95": "surah-at-tin",
    "96": "surah-al-alaq",
    "97": "surah-al-qadr",
    "98": "surah-al-bayyinah",
    "99": "surah-az-zalzalah",
    "100": "surah-al-adiyat",
    "101": "surah-al-qariah",
    "102": "surah-at-takathur",
    "103": "surah-al-asr",
    "104": "surah-al-humazah",
    "105": "surah-al-fil",
    "106": "surah-quraysh",
    "107": "surah-al-maun",
    "108": "surah-al-kawthar",
    "109": "surah-al-kafirun",
    "110": "surah-an-nasr",
    "111": "surah-al-masad",
    "112": "surah-al-ikhlas",
    "113": "surah-al-falaq",
    "114": "surah-an-nas"
};

// Map Slug (string) -> ID (number)
export const SURAH_SLUG_TO_ID: Record<string, number> = {
    "surah-al-fatihah": 1,
    "surah-al-baqarah": 2,
    "surah-ali-imran": 3,
    "surah-an-nisa": 4,
    "surah-al-maidah": 5,
    "surah-al-anam": 6,
    "surah-al-araf": 7,
    "surah-al-anfal": 8,
    "surah-at-tawbah": 9,
    "surah-yunus": 10,
    "surah-hud": 11,
    "surah-yusuf": 12,
    "surah-ar-rad": 13,
    "surah-ibrahim": 14,
    "surah-al-hijr": 15,
    "surah-an-nahl": 16,
    "surah-al-isra": 17,
    "surah-al-kahf": 18,
    "surah-maryam": 19,
    "surah-taha": 20,
    "surah-al-anbya": 21,
    "surah-al-hajj": 22,
    "surah-al-muminun": 23,
    "surah-an-nur": 24,
    "surah-al-furqan": 25,
    "surah-ash-shuara": 26,
    "surah-an-naml": 27,
    "surah-al-qasas": 28,
    "surah-al-ankabut": 29,
    "surah-ar-rum": 30,
    "surah-luqman": 31,
    "surah-as-sajdah": 32,
    "surah-al-ahzab": 33,
    "surah-saba": 34,
    "surah-fatir": 35,
    "surah-ya-sin": 36,
    "surah-as-saffat": 37,
    "surah-sad": 38,
    "surah-az-zumar": 39,
    "surah-ghafir": 40,
    "surah-fussilat": 41,
    "surah-ash-shuraa": 42,
    "surah-az-zukhruf": 43,
    "surah-ad-dukhan": 44,
    "surah-al-jathiyah": 45,
    "surah-al-ahqaf": 46,
    "surah-muhammad": 47,
    "surah-al-fath": 48,
    "surah-al-hujurat": 49,
    "surah-qaf": 50,
    "surah-adh-dhariyat": 51,
    "surah-at-tur": 52,
    "surah-an-najm": 53,
    "surah-al-qamar": 54,
    "surah-ar-rahman": 55,
    "surah-al-waqiah": 56,
    "surah-al-hadid": 57,
    "surah-al-mujadila": 58,
    "surah-al-hashr": 59,
    "surah-al-mumtahanah": 60,
    "surah-as-saf": 61,
    "surah-al-jumuah": 62,
    "surah-al-munafiqun": 63,
    "surah-at-taghabun": 64,
    "surah-at-talaq": 65,
    "surah-at-tahrim": 66,
    "surah-al-mulk": 67,
    "surah-al-qalam": 68,
    "surah-al-haqqah": 69,
    "surah-al-maarij": 70,
    "surah-nuh": 71,
    "surah-al-jinn": 72,
    "surah-al-muzzammil": 73,
    "surah-al-muddaththir": 74,
    "surah-al-qiyamah": 75,
    "surah-al-insan": 76,
    "surah-al-mursalat": 77,
    "surah-an-naba": 78,
    "surah-an-naziat": 79,
    "surah-abasa": 80,
    "surah-at-takwir": 81,
    "surah-al-infitar": 82,
    "surah-al-mutaffifin": 83,
    "surah-al-inshiqaq": 84,
    "surah-al-buruj": 85,
    "surah-at-tariq": 86,
    "surah-al-ala": 87,
    "surah-al-ghashiyah": 88,
    "surah-al-fajr": 89,
    "surah-al-balad": 90,
    "surah-ash-shams": 91,
    "surah-al-layl": 92,
    "surah-ad-duhaa": 93,
    "surah-ash-sharh": 94,
    "surah-at-tin": 95,
    "surah-al-alaq": 96,
    "surah-al-qadr": 97,
    "surah-al-bayyinah": 98,
    "surah-az-zalzalah": 99,
    "surah-al-adiyat": 100,
    "surah-al-qariah": 101,
    "surah-at-takathur": 102,
    "surah-al-asr": 103,
    "surah-al-humazah": 104,
    "surah-al-fil": 105,
    "surah-quraysh": 106,
    "surah-al-maun": 107,
    "surah-al-kawthar": 108,
    "surah-al-kafirun": 109,
    "surah-an-nasr": 110,
    "surah-al-masad": 111,
    "surah-al-ikhlas": 112,
    "surah-al-falaq": 113,
    "surah-an-nas": 114
};

// Helper
export function getSurahSlug(id: number): string {
    return SURAH_ID_TO_SLUG[id] || id.toString();
}

export function getSurahIdFromSlug(slug: string): number | null {
    // If it's a number string "1", accept it too for backward compat if needed? 
    // Or strict slug only. Let's try strict first, but safe.
    if (SURAH_SLUG_TO_ID[slug]) return SURAH_SLUG_TO_ID[slug];
    
    // Maybe it's a number?
    const parsed = parseInt(slug);
    if (!isNaN(parsed) && parsed >= 1 && parsed <= 114) return parsed;
    
    return null;
}
